language: cpp

matrix:
  include:
    - os: linux
      env: BUILD_TARGET=3.7
    - os: linux
      env: BUILD_TARGET=3.6
    - os: linux
      env: BUILD_TARGET=2.7
    - os: osx
      env: BUILD_TARGET=3.7
    - os: osx
      env: BUILD_TARGET=3.6
    - os: osx
      env: BUILD_TARGET=2.7
#    - os: windows
#      env: VC_VERSION=msvc-14.0 BUILD_TARGET=3.7
#    - os: windows
#      env: VC_VERSION=msvc-14.1 BUILD_TARGET=3.7
#    - os: windows
#      env: VC_VERSION=msvc-14.2 BUILD_TARGET=3.7
#    - os: windows
#      env: VC_VERSION=msvc-14.0 BUILD_TARGET=2.7
#    - os: windows
#      env: VC_VERSION=msvc-14.1 BUILD_TARGET=2.7
#    - os: windows
#      env: VC_VERSION=msvc-14.2 BUILD_TARGET=2.7
#    - os: windows
#      env: VC_VERSION=msvc-14.0 BUILD_TARGET=3.6
#    - os: windows
#      env: VC_VERSION=msvc-14.1 BUILD_TARGET=3.6
#    - os: windows
#      env: VC_VERSION=msvc-14.2 BUILD_TARGET=3.6
      
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$BUILD_TARGET 
  - conda activate test-environment
  - conda install conda-build anaconda-client
  - anaconda config --set auto_register yes
  - conda config --set anaconda_upload yes
  - anaconda login --password ${ANACONDA_PASSWORD} --username ${ANACONDA_LOGIN}

script:
  - cd repice  
#  - conda-build . -c conda-forge
  - echo "OK"
  