language: python

matrix:
  include:
    - os: linux
      python: 3.7 
    - os: linux
      python: 3.6 
    - os: linux
      python: 2.7 
    - os: osx
      python: 3.7 
    - os: osx
      python: 3.6 
    - os: osx
      python: 2.7 
    - os: windows
      env: VC_VERSION=msvc-14.0 TRAVIS_PYTHON_VERSION=3.7
    - os: windows
      env: VC_VERSION=msvc-14.1 TRAVIS_PYTHON_VERSION=3.7
    - os: windows
      env: VC_VERSION=msvc-14.2 TRAVIS_PYTHON_VERSION=3.7
    - os: windows
      env: VC_VERSION=msvc-14.0 TRAVIS_PYTHON_VERSION=2.7
    - os: windows
      env: VC_VERSION=msvc-14.1 TRAVIS_PYTHON_VERSION=2.7
    - os: windows
      env: VC_VERSION=msvc-14.2 TRAVIS_PYTHON_VERSION=2.7
    - os: windows
      env: VC_VERSION=msvc-14.0 TRAVIS_PYTHON_VERSION=3.6
    - os: windows
      env: VC_VERSION=msvc-14.1 TRAVIS_PYTHON_VERSION=3.6
    - os: windows
      env: VC_VERSION=msvc-14.2 TRAVIS_PYTHON_VERSION=3.6
      
install:
  - echo $TRAVIS_PYTHON_VERSION
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then echo $VC_VERSION; fi
  #- sudo apt-get update
  #- wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #- bash miniconda.sh -b -p $HOME/miniconda
  #- source "$HOME/miniconda/etc/profile.d/conda.sh"
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  #- conda info -a
  #- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  #- conda activate test-environment
  #- conda install conda-build anaconda-client
  #- anaconda config --set auto_register yes
  #- conda config --set anaconda_upload yes
  #- anaconda login --password ${ANACONDA_PASSWORD} --username ${ANACONDA_LOGIN}

script:
  #- cd repice
  #- conda-build . -c conda-forge
  