package:
  name: lib_boost
  version: 1.70.0

source:
  fn: boost_1_70_0.tar.bz2
  sha256: 430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778
  url: https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2

requirements:
  host:
    - python
    - numpy

  build:
    - python

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: lib boost 1.70.0 compiled with gcc 5.4.0 under ubuntu16.04 with python 3.6
