package:
  name: libboost_python
  version: 1.70.0

source:
  fn: boost_1_70_0.tar.bz2
  sha256: 430ae8354789de4fd19ee52f3b1f739e1fba576f0aded0897c3c2bc00fb38778
  url: https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2

build:
  features:
    - vc{{vc}} [win]

requirements:

  host:
    - python
    - numpy
    - libiconv          [osx]

  run:
    - python
    - numpy

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Boost provides free peer-reviewed portable C++ source libraries. This package include all boost lib with especially boost_python and boost_numpy
